language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
  # - "3.7-dev" # 3.7 development branch
# Django versions to run tests
env:
  - DJANGO_VERSION=1.10.6
  - DJANGO_VERSION=1.10.7
  - DJANGO_VERSION=1.11
# command to install dependencies
install: 
  - pip install -r requirements.txt
  - pip install -q Django==$DJANGO_VERSION --use-mirrors
  - pip install pep8
  - pip install pyflakes
before_script:
  - pep8 --exclude=migrations main --ignore=E128,E127
  - pep8 --exclude=migrations StalkerShop --ignore=E128,E127
  - flakes main
  - flakes StalkerShop
  # - mysql -u root -p'destacame' -e 'create database test_stalkershop;'
# command to run tests
script: 
  - python manage.py test
