language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7-dev" # 3.7 development branch
# command to install dependencies
install: "pip install -r requirements.txt"
# command to run tests
script: pytest
env:
  - DJANGO_VERSION=1.10.1
  - DJANGO_VERSION=1.10.2
  - DJANGO_VERSION=1.10.3
  - DJANGO_VERSION=1.10.4
  - DJANGO_VERSION=1.10.5
  - DJANGO_VERSION=1.10.6
  - DJANGO_VERSION=1.10.7
  - DJANGO_VERSION=1.11
install:
  - pip install -q Django==$DJANGO_VERSION
