language: python
python:
  # - "2.7"
  - "3.4"
  # - "3.5"
  # - "3.6"
  # - "3.7-dev" # 3.7 development branch
# Django versions to run tests
env:
  # - DJANGO_VERSION=1.10.4
  # - DJANGO_VERSION=1.10.5
  # - DJANGO_VERSION=1.10.6
  # - DJANGO_VERSION=1.10.7
  - DJANGO_VERSION=1.11
# command to install dependencies
install:
  - cd backend
  - pip install -r requirements.txt
  - pip install -q Django==$DJANGO_VERSION
  - pip install pep8
  - pip install pyflakes
before_script:
  - pep8 --exclude=migrations main --ignore=E128,E127
  - pep8 --exclude=migrations StalkerShop --ignore=E128,E127
  - pyflakes main
script:
  - python manage.py test'
deploy:
  provider: elasticbeanstalk
  access_key_id: AKIAIWGSBV7J5WPX764Q
  secret_access_key:
    secure: fVkJh3qGlHVojY2IjJthOvCEjj6BaxaEydPSaZy71cmKyHm0MIHvDakE4GPOJRlsnLzSmPmAOuK8/8JDCJzK0BQq4G6Sn0bMrGlSWL1ytQCYkQVqKQMMa/2hW4joMjFpzflU6s8e0b43kmxHsJPl+CUJSVUveyGGeLO/iaidT+C2SLibbTLoH64hG+EgB+zIk3LqePp/vHxGapOy9sv1fVCrpTPQBCJX5JrRUVdt9eZGh7JqkB5yGlucc7RYjLA1H6p1tM8IeW4d7be/tFyupD5nUGW9LyAi3Z4JsQi2QAIXF8gbjgugLi5ETJe9WxzrsF3zlLg6i8OMnDullwJkfwPFvdGWcTH15nVupTLPmcHlUosv9gD53XtMMlSC+fVbCiNxZdwocq06ysSPZy7fXnjQwuW0OHAcmfWSzkCG8IAwwGFfT5GY8CIuL9zYM6/hMqW5+lYEeT/ees+c0505jpxYaE36Bly4yWG/nWmWphz1yyMzovh3a7O5OKrrxZqeDoZtWtaFsYhn2N6B7WGxxI7p8bjg5sjj5gpgP9BISL3LpmnVcWVGwtzFWrob34/f3oddyeZLO++ebdp/n/2M67GQ1g1wG5KcrlB8ukbvy8Bbu5uT2PkY2VhxU5+O90FTgyTnTO5CCy2d42qayKNhjvr0rVkCyJmkl91CnT7PYhM=
  region: us-west-2
  app: StalkerShop
  env: ProductionEnv
  bucket_name: "elasticbeanstalk-us-west-2-906307946871"
  on:
    repo: gruizmir/StalkerShopBackend
    branch: dev
