# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-15 04:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('url', models.URLField(max_length=300, verbose_name='URL')),
                ('sku', models.CharField(blank=True, max_length=30, null=True, verbose_name='SKU')),
                ('store', models.CharField(choices=[('falabella', 'Falabella'), ('ripley', 'Ripley'), ('paris', 'Paris'), ('sodimac', 'Sodimac'), ('easy', 'Easy'), ('hites', 'Hites'), ('abcdin', 'Abcdin')], max_length=200, verbose_name='Store')),
                ('price_1', models.IntegerField(verbose_name='Price_1')),
                ('price_2', models.IntegerField(verbose_name='Price_2')),
                ('price_3', models.IntegerField(verbose_name='Price_3')),
                ('published_discount', models.IntegerField(blank=True, null=True, verbose_name='PublishedDiscount')),
                ('calc_discount', models.IntegerField(blank=True, null=True, verbose_name='PublishedDiscount')),
                ('image_url', models.URLField(max_length=300, verbose_name='ImageURL')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
    ]
