# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-06 16:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='calc_discount',
            field=models.IntegerField(blank=True, null=True, verbose_name='RealDiscount'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_2',
            field=models.IntegerField(blank=True, null=True, verbose_name='Price_2'),
        ),
        migrations.AlterField(
            model_name='product',
            name='store',
            field=models.CharField(choices=[('falabella', 'Falabella'), ('ripley', 'Ripley'), ('paris', 'Paris'), ('sodimac', 'Sodimac'), ('easy', 'Easy'), ('hites', 'Hites'), ('abcdin', 'Abcdin'), ('pcfactory', 'PcFactory')], max_length=200, verbose_name='Store'),
        ),
    ]
