# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-06 19:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20170506_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image_url',
            field=models.URLField(blank=True, max_length=300, null=True, verbose_name='ImageURL'),
        ),
    ]
